### ISSUE TITLE
heat map does not reflect contour level

### ISSUE THREAD

**Issue by lpravda** [ondraab/ramachandran#2]
There is a possible rounding issue for certain heatmaps. e.g. contour level does not reflect the heat map for the all but general case and cis-proline. (heat map is in some cases less restrictive and in others less permisive). Pictures for comparison attached.
![screen shot 2018-06-29 at 14 40 27](https://user-images.githubusercontent.com/16133456/42095405-6f1840b4-7baa-11e8-9984-a3ef74ea213c.png)
![screen shot 2018-06-29 at 14 40 35](https://user-images.githubusercontent.com/16133456/42095406-6f3981fc-7baa-11e8-942b-f72caea6eb20.png)

**Comment by ondraab** [comment]
There might be a problem with contour settings, working on fix.
